### ISSUE TITLE
Sorted Rows Inconsistent on Refresh

### ISSUE THREAD

**Issue by TylerMillis** [geoffreylitt/wildcard#11]
### Problem
After sorting a column and then refreshing the page, the resulting page has some bugs with what the sorted rows should now look like. The best way to describe the behavior is going through specific cases and my guesses at what is going wrong.

1. YouTube. If you sort by title and then refresh, the videos and table rows rearrange as wanted. If you have any user columns entered, they also appear correctly. Upon clicking on the page (which runs a reload of the data), the user columns become unsorted (back to their original state for sorting). I believe this is because of how reloadData works, somehow when it reloads the data it doesn't reorganize the local data of the user.
2. Weather Channel. If you sort by time and then refresh, the rows rearrange for a split second, and then go back to the website's original sort. The table rows appear correctly, but open clicking on the website (which runs a reload), the table rows show the same ordering of the website, even though the sort should still be applied.
3. Airbnb. If you sort by rating and then refresh, the listings are rearranged in order, but the table rows are not in the correct ordering until you click on the page (which runs a reload of the data). 

It seems like these may be three separate issues, but I feel like they are similar enough they may have a similar solution.

**Comment by geoffreylitt** [comment]
I will look into these (together with #13) this coming week
