### ISSUE TITLE
User Column Data Disappears on Reload

### ISSUE THREAD

**Issue by TylerMillis** [geoffreylitt/wildcard#13]
### Problem
After adding in data, formula or text, to a user column, it will be erased on reload. This is especially an issue with sites that reload on click or keydown since they are constantly checking for new rows, but is not an issue with site adapters like Hacker News since they are static.

### Solution
This issue appeared after the change to reloadData that allows new rows after the initial loading of data. The function now retrieves the new rows from the site adapter and puts them in the table instead of merging the user data as well. The solution should be a better way to allow new rows, but keep existing user data as well.

**Comment by geoffreylitt** [comment]
to clarify: this is a known issue, we understand why it's happening. just need to fix
