### ISSUE TITLE
Doesn't run on FF or Chromium??

### ISSUE THREAD

**Issue by canDry** [geoffreylitt/wildcard#30]
In FF 76:  
`uncaught exception: Unable to load script: moz-extension://beb8ade5-6752-4bc8-9270-26388fc160a6/dist/wildcard.js SyncMessage.js:238:15 ` 

In Chromium 71:  
Doesn't open the manifest.

**Comment by geoffreylitt** [comment]
@canDry thanks for filing this issue!

Could you tell me how you attempted the install? Looking at the error I'm wondering if maybe you cloned the git repo and tried to install it directly? If so, that won't work because this is just a source repo and isn't a bundled/compiled output.

There are two ways to install that should work:

1) Download a compiled release: https://geoffreylitt.github.io/wildcard/#/quickstart
2) Build from source: https://geoffreylitt.github.io/wildcard/#/devenv

Let me know if that helps or if there's still a problem!

**Comment by canDry** [comment]
Very sorry 'bout not following the instruction i.e. using the release. Though the release is only at v0.2 and seems to be missing many features that are shown in your talk.  Well, unless I am again missing something obvious!  :)

FYI...I thoroughly enjoyed your talk about the underlying components of wildcard and the followup.  Both you and Kartik aptly noted that browsers are moving targets and extensions continually break because of every increasing privacy restrictions.  In addition, websites change their css selectors which means the site adapters must be maintained.  I think this is why grease/tampermonkey (incredibly useful tools as you noted) eventually lost their audience.

Some ways I'd like to use this tool:
- progress thru multiple pages of txns to search for matching desc (via regex) and amount (via range)
- filter a store's content to only display previously selected or matching products (via regex on the desc) that meet a target price (via range)
- keep track (persistent over time) and display of the number of times an item on a page has been presented - i.e. to allow filtering e.g. exclude (or grey out) items that have already been presented/displayed x times

Desired features:
- provide a method to view and save the extracted data (e.g. json, csv) 
- ability to export to airtable and/or google sheets would be a massive bonus

I hope you and your team will keep up the great effort on this game changing tool!

**Comment by geoffreylitt** [comment]
Yes you're right that it's missing features from the talk. I did a total rewrite of the extension to improve stability and still catching up to the full feature scope -- hoping to get there in the next month or so.

Thanks for those thoughts on feature requests. CSV / Google Sheets export makes total sense and is easy to add to the todo list. The even cooler thing would be to use Google Sheets as a UI to actually edit websites, but not sure how feasible that is...
